[versions]
# Build Tools
agp = "8.13.0"
kotlin = "2.2.21"

# Compose & UI Framework
composeMultiplatform = "1.9.2"
uiBackhandler = "1.9.2"

# AndroidX - Core
annotation = "1.9.1"
appcompat = "1.7.1"
coreSplashscreen = "1.0.1"

# AndroidX - Activity & Lifecycle
androidx-activity = "1.11.0"
androidx-lifecycle = "2.9.5"

# Navigation
navigationCompose = "2.9.1"

# Image & Media
androidPdfview = "3.2.11"
kmpCapturableCompose = "0.1.1"
krop = "0.2.0"


[libraries]
# Build & Language
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# AndroidX - Core
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# AndroidX - Activity & Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

# AndroidX - Lifecycle
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# Navigation
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

# Compose UI Framework
ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "uiBackhandler" }

# Image Processing & Capture
android-pdfview = { module = "com.github.Infomaniak:android-pdfview", version.ref = "androidPdfview" }
kmp-capturable-compose = { module = "io.github.suwasto:kmp-capturable-compose", version.ref = "kmpCapturableCompose" }

# Image Cropping (Krop)
krop-core = { module = "com.attafitamim.krop:core", version.ref = "krop" }
krop-ui = { module = "com.attafitamim.krop:ui", version.ref = "krop" }


[plugins]
# Android Gradle Plugin
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

# Kotlin Multiplatform
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

# Compose & Compiler
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
